name: Flutter Lint Check

on:
  pull_request:
    branches:
      - homepage
  push:
    branches:
      - homepage

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5' # Replace with the desired Flutter version
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        
      - name: Run Flutter analyze
        id: analyze
        run: flutter analyze
