name: Flutter Lint Check

on:
  pull_request:
    branches:
      - homepage
  push:
    branches:
      - homepage

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10' # Replace with the desired Flutter version

      - name: Install dependencies
        run: flutter pub get
        
      - name: Run Flutter analyze
        run: flutter analyze
        
      - name: Comment lint results
        uses: actions/github-script@v4
        with:
          script: |
            const results = `$(flutter analyze)`;
            const octokit = github.getOctokit({ secrets.Token });
            const context = github.context;
            await octokit.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: output
            });
