name: Flutter Lint Check

on:
  pull_request:
    branches:
      - homepage
  push:
    branches:
      - homepage

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ${{ env.HOME }}/sdks/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Set up Flutter
        run: |
          export PATH="${{ env.HOME }}/sdks/flutter/bin:${{ env.PATH }}"
          flutter doctor

      - name: Install dependencies
        run: flutter pub get
        
      - name: Run Dart analyze
        id: analyze
        run: dart analyze
