name: Flutter Lint Check

on:
  pull_request:
    branches:
      - homepage
  push:
    branches:
      - homepage

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10' # Replace with the desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter analyze
        id: analyze
        run: |
          output=$(flutter analyze) || echo "::set-output name=analysis_result::error"
          if [[ $output != "No issues Found!" ]]; then
            exit 1
          else
            echo "::set-output name=analysis_result::$output"
          fi

  comment_on_commit:
    needs: analyze
    runs-on: ubuntu-latest

    steps:
      - name: Comment on lint result on commit
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const output = `${{ needs.analyze.outputs.analysis_result }}`;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const context = github.context;
            await octokit.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: output
            });
